FROM alpine:latest

RUN apk --no-cache --update add bash tzdata openssl jq
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /root
VOLUME /mnt/data

COPY certs-extraction.sh /root/certs-extraction.sh
COPY healthcheck /usr/bin/healthcheck
RUN chmod +x /usr/bin/healthcheck
RUN chmod +x /root/certs-extraction_itsltn.sh

CMD ["/bin/bash", "/root/certs-extraction_itsltn.sh"]